export const forecastConstants = {
    FETCH_FORECAST_REQUEST: "FETCH_FORECAST_REQUEST",
    FETCH_FORECAST_SUCCESS: "FETCH_FORECAST_SUCCESS",
    FETCH_FORECAST_FAILURE: "FETCH_FORECAST_FAILURE",
    UPDATE_DAY_FORECAST:"UPDATE_DAY_FORECAST"
}